version: "3"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 7306:3306
    volumes:
      - mysqldata:/var/lib/mysql/data

  php:
    image: drupal:$DRUPAL_TAG
    #container_name: "${PROJECT_NAME}_drupal"
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    ports:
      - 8080:80
    links:
      - mariadb:mysql
    volumes:
      - drupal-install:/var/www/html

  nginx:
    image: nginx:$NGINX_TAG
    #container_name: "${PROJECT_NAME}_nginx"
    links:
      - php
    ports:
      - $NGINX_PORT
    volumes:
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - drupal-install:/var/www/html
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html

  #node:
  #  image: "node:14.9.0"
  #  user: "node"
  #  working_dir: /home/node/app
  #  environment:
  #    - NODE_ENV=production
  #  volumes:
  #    - ./:/home/node/app
  #  expose:
  #    - "8081"
  #  command: "npm start"

volumes:
  mysqldata: {}
  drupal-install: {}